version: '3.8'

services:
  # Cliente para koryubudo
  koryubudocliente:
    container_name: koryubudocliente
    image: koryubudocliente:latest
    build:
      context: ../SoloQAmateurCliente
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "7565:7565"
    environment:
      - DOCKER_CONTAINER=1
    networks:
      - koryubudo_network

  # API para koryubudo
  koryubudoapi:
    container_name: koryubudoapi
    image: koryubudoapi:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "7566:7566"
    environment:
      - DOCKER_CONTAINER=1
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${CONTRASENASQL}
      - DB_NAME=soloqamateur
    restart: always
    env_file:
      - .env
    networks:
      - koryubudo_network
    command: /bin/sh -c "npm start"

networks:
  koryubudo_network:
    external: true
